version: '2'
services:
    mongo:
        container_name: body101_mongodb
        image: mongo
        ports:
            - "27017:27017"
    app:
        container_name: body101_web_app
        build: .
        env_file: .env
        ports:
            - "5000:5000"
        volumes: 
            - .:/src
        links:
            - mongo
        depends_on:
            - mongo