version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - birthdates_api-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - birthdates_api-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: birthdates_api-{{ checksum "package.json" }}
        
      # run linting!
      - run: npm run linting

    deployment:
      staging:
        branch: dev
        heroku:
          appname: birthdates-api
